server:
  port: 8888

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

datasource:
  fastcafe-admin:
    url: jdbc:log4jdbc:mysql://test-db.ones.cloud:3306/fastcafe_admin?useSSL=false&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: test_ones_aws
    password: ffei32##2nd!$%
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  fastcafe-log:
    url: jdbc:log4jdbc:mysql://test-db.ones.cloud:3306/fastcafe_log?useSSL=false&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=UTF8
    username: test_ones_aws
    password: ffei32##2nd!$%
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            DriverManagerDataSource: DEBUG
    org.hibernate.SQL: DEBUG
  config: classpath:logback.xml

jwt:
  secret:
    key: osteam##qovh